services:
  - type: web
    name: spring-boot-app
    runtime: java
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/emaildemo-0.0.1-SNAPSHOT.jar
    region: oregon